### ISSUE TITLE
las file  header scale is not used

### ISSUE THREAD

**Issue by Casual2017** [VUKOZ-OEL/3d-forest#3]
The function LasFile::transfor is defined, why not called it? the coordinates not equal to real value.

**Comment by VaclavBubnik** [comment]
Graphic card hardware is usually limited to rasterize vertices in floats. Scaling of las coordinates with scale factor creates uncomfortable visual artifacts for some datasets in the current version of 3D Forest due to limited precision of 32-bit floating numbers. 3D Forest performs all calculations in double precision floating-point type (64-bit), but uses single precision floating-point type (32-bit) to display point clouds on screen.

**Comment by Casual2017** [comment]
Thinks a lot
